jobs:
  include:
  - stage: Roaster
    language: node_js
    node_js:
    - "10"
    sudo: false
    before_install:
    - cd ./www
    script:
    - npm run build
    - npm test

  - stage: Roaster
    language: go
    sudo: false
    go:
    - 1.11.x
    env:
    - GO111MODULE=on
    install: skip
    script:
    - travis_retry go build github.com/LuleaUniversityOfTechnology/2018-project-roaster/cmd/...
    - go test -v -cover -race -covermode=atomic -coverprofile=profile.cov ./...
    - travis_retry go run golang.org/x/lint/golint -min_confidence 0.0 -set_exit_status ./...
    after_success:
    - travis_retry go run github.com/mattn/goveralls -coverprofile=profile.cov -service=travis-ci

  - stage: Deploy
    if: branch = master AND type = push
    sudo: required
    services:
    - docker
    before_install:
    - mkdir build
    script:
    - docker run --rm -v "$PWD/www":/usr/src/roaster -w /usr/src/roaster node /bin/bash -c "npm install && npm run build" && cp -r ./www ./build/www
    - docker run --rm -v "$PWD":/usr/src/roaster -w /usr/src/roaster/cmd/roasterd golang:1.11 go build -o /usr/src/roaster/build/roasterd
    - du -h -d1 build/*
    - docker build -t roaster .
    before_deploy:
    - git add --force build Dockerfile
    deploy:
      provider: elasticbeanstalk
      edge:
        branch: ebignore
      access_key_id:
        secure: MnyzuNOu1Kwj3Ol6msXAiEDbiXaY24xPxJzbBXd9ZG3k9NR7G3O/aHPEFeeYQ13VTPZL9/+YaS+tU9Hxv79DoVup7ZyeO/P8jsmn2vAUrSH2tBQLB6IEk0yFo5tU45JTU0O/Nf2+MFcWlpHavKaUL2pwxMlftn00+WHe4jqCgGYy2bcxYeIbC6D3J59mTb8i18SzAGopx5HoOGRmfUbg3VHD0kQOEuRACmHKI0XbkfTI7BRQr/Tbmvk69lOmA5XnHdVilv+gtB+zWmDujjOYn5wRKf4o2NKQbyO5qbV5y/6/trloKKQHZHT1tPDOKeb6lkRva4fvYP6WBF70HklapxBIgBZs+2lWUidkIxBVrV/uDXbyenvpFi7K1NQ66VowMW+dahCf6yP0A6lmfYLRIyl80dBNvcdtkxdhjIfFQjn+s2LnRNOeYsNZDgkDeIEibaSrIAmI1dTh0LROlCNAUrOnFhBuUmx9fow83HLKS0HXHIRLDGdSP2jFGMflguizz5zJx4YRDz9nrSpu0BbKnF1hT64H1j6Yv4Gyg+xOC3cmwByybnXUrK4L6LnLaseQY6D8YCjFn3ZGrP0FKKf8x4wBQXJQ/hniqtkxrrRUtpQxndx/uDgt6/ZVRXShZRINjW8k4eQeJezQ0Zm+RvGgviZY0ArFqYmSeLR22sgu09I=
      secret_access_key:
        secure: dZNfl7gK3FO8nuqrkemG8/EHeGxLSDObO4klPf1BlETNxUyBJtLITFBebjZGXkZlYdinTdnxlWIr/esLx4TynONvKo0kqjTs18OOBdy1caLeY58vhLxxH9bL7GcmPltoiV42eO8ErThU8dnuPyep/ww+gSAyARV5lw7ChQ3LTqTHVQf7rzpWsMy86tmZhKZCzTHVi0oNTUeCow6GVsYTgCBnX8wPlmh62ubevPYWzeoqvFpIO+5Gqo57Se2qN9k2l8NBO1LKR7MgBrdduIbezNawmr0ru5gV/chVLPNTxKzET7mepQ57JHEY3RvTBWC00XYcQsf4jAK8U3yfdqUmjQ+uSsRgOg13wjEVKBFILI2yIT0916KM7SUnOXop6nYY/BmtQ+TG2SdfSQC6vJnCNzlcrg+Vhh6tnoEW9LdsnxcyWGYpWtpn9h5lPKu4XU5dlfMGRGGhMrukQNgIMLZ3+Jjmq0bfxjQEs+Y4xuXeMtG7YOf+4/1I0KT3XsyZBWtqmUTb3+Ab6yuWK98j9a+8kgnLSWgqtZebS9VPIzo71sO1M4kMR2nSWe5mZbMFnAWypS/DvacnrvX+viU6u9nXXaS1/8R75lli61mRUw/rGiqwjPePUVVgWApuHw5MmRm9EJ8cercEp14gedH0UsWmnXQu2NuzaAb+l02S/CPBpSE=
      region:
        secure: vKEoHpuIB+Q0M5pxyvfcnhwK+2gKenyWosTVkNhSFTC86DgkliK1BIC3rmba60lmFKXpnSVLFB0R4QvGU0mFXpyzj30Je9X4JGtEJT0B6d6K8MLm2uHxJOhXHRt82kZneK845jvZjbPJRf0fwmc/v067hOchpE/KItI3z6SCkV4foVOpqvVZsEn3xaHDThPWEtZX5kWlZFfLPlJwXij5XBy8NXMmlTu/8ygmhIzHcJ5bZB0EiqJyXroONiY6bpn/Mu3rovi/+ebJc+YKnJ+QSJK9KUV17D4+AAvX5lXja6rbthKnhUpDtbyp/wshxfMeA4IXTOIW3Z8cAfiQesQHlVE09e7UnmDyjp2Pkp3rli9S8yI6dV4XvYX6q+q9BUNHc9gvTwQU+lY8Jy+nROBSVqSUxf++3Cxuizahxe2Cpafsil571VBL6MtPLWAgu3+SKG/cMwnQDocWXrZ0wfBOwR3qH3+N1hvN9RAPAFi41+iwqdaE+79+hqgrV9d8q+fc9if3rzF5JIzbCUSRdn63+52uS7V/1lYcjXKkI4EPHTiRvG4Wq22KIFM41D59OPeX/1stH6cAR2dcJfDZWa65UBXhgOfrPeg7a5XPrmcXyLTqdzIcAQaKWPHxKPKBOXzII9Lxta3wwtxTDc7TZWObeZRjJt+h0L9Tw7uU6xTtZVs=
      app:
        secure: epG569dSFpKFkH9/di2Eee1lN5/y8kufYPLs8nik6sHL8H7ip5VHGHxfYolyMoP7if9kNkKmhs/qFmeKYo/3Ioe1iICq1mr2bLP01ZY5nV9dkO8fIHioief3uVQF3HmeQ6KzkpZ7uZ1Uj/HBEcLXU7V9CTq0mj1wOnuBbsYZz1gt5rXqfCG++Zc6E2ljFIfoL/PZuqx0rriaPqxSaScZ5/65jrr2qdUb3rj8ET9Cx7rV4VR+WCUR5UY2omFK9/EASpTSr45tslPMcyc3Lwx3Plh9kf68g5IWt5KLjGsnEbiy/VXGB74W4GIrpbhYtP0VocsAY0qUr9zHXl4nnIraPs27DptwrwjGz6GB007s1IamdYN2/PAGxK3WgmJAkN4Ul/Ih+iTLhUsaVjqUnX5+xPS0Kiqezs26Cmraur4V1iR0EuClEjeNlpF6IgV7hU1qzBs+C1wxq07FTb6V/0FeN5A+myOlEW8SzDpV4wkvhyurLUGQrBh7+YaoUBwleMKIRMR6Havu9mQMXY+GNgKEdkJO1EzIgvaP2UXYH3xW0qP+QrV4Ip1Fb/ZtZu/9KrZwUaMckLAsAn927USQhhBHb568FQZFxDo5fDKuOKgmjJ7Itvn2AMzmxU1Ggn8BxrwITPO3kZPGHihJ0DzLdYOAt/kpcIDOq5Qpmm7Ygw1NnKI=
      env:
        secure: xiH0ewBUh5WyzFk10rwGiCiMfdL+KStBmSClHaQPDlg5L7VNoZT21dJBWD1VaBdNAwrK/qG0hzg+LJ1kIupnHlWZcVCBC0ViPOwNub30uUUs6JblkL4j2NSO5GxFwoazZjrGZ+LaF5WNDZAyH5rTefY1TiMILzVgRdA3BnpCMcj8BA1l6jdJKBvDR3kjcTVfm4SWR+Os0kx1O5RQ5U6KJMCrYiQia4F0qDy9SjMacTpAAprexeN4BxpDVp4bpb75Zp7l9abQNGheNh92SZ0KMl4/bNvtvIVSctlZKcv4uvtoZmmwkQBhPFf6i7dMYEXhsj7aHy6C5CAy0dfuIjPpLH9JB33AnTExbLrsJgUE8S0n9rsWRH7B1rZ9Xo9KIwrirbhcOGGd5BnVIYoC5YSSYZkiIzQPDJO+PaJMkV/UY6YikIvLUMHzer842At7MO7ZfvnQcVTGP0XAQ5qswE8TmKDjRpG5UmcZfWfEJsrbbRVci8zn1rG6Y3jtjb118Msmo/POmqsSjxXYJCBimzqvFRkx31Jyj+awAR4hdWJ01Gb0x4ZLLexbR7EQRz57bCA9c/Wu/IcomsfGph4fGxLiofW/FA1zJQRqnf/rhskkHRJHFqhw6lesXaFKeMLz+pxrIXRuCzi0RkSflUuNhfn1E5KqaqI64sFJBAFQNy0DozI=
      bucket_name:
        secure: TVD0mXwAkrm/xnnIf4PuKwQvzfjSvnGSFOuYLjB4LW854LhIBzaZ7sWd0vGdPM/1/S4R8NYEtw9aZozrl9a8yk+g1HT4+NICmkHaEaOa6fAA9mMnLZxPDGF1Dwk9kowMk3O2ZrxJl6pO0M7Ww/VU+T5zyS+j7ydEYT1peHsGtEQF06PTzSEp4fzeoM1MS7PpTpbwNmIdv4BypDaXTwuQxBfuqgoQ9ALOHW+kCXxxpm4CEWGaYFIjMWghrPY3biiiwqDdbR+mc++8/lWDDo5W/0k0iEJkIfGFh8aWcG/LQ4UlzVcRkz6dTRTPtYnjMD3iSRdhivL7vM1756JV0WRNpEWe+77J1Ewv8hI76UIX353Ngh8KKFPHQrfDWJ16yFdK+EbjFD4og/XYpaJUuD2UxUGUWYP+SbsqUsvq/02kE5ju+I4JuiD8+D8i+mvfSVs0hgOueTj70VmhGwH0RfTlJ4mjL8T6ahjQx2l1ymmqyYteMgEoKnXIcpEg5ysplRsxwbiDNzVVBqLw16Lmq2H9c/tZlXlDCSwAljv7ZxGQUArrCUfFU8iUuwzTCMqK0vSz+uptJVeNZfehfmdvzEnJsg7XX8WJOZI7uojlRI0BVS6JOrniwDuXFJ9R8pbZiuAgbNjnvWnXZNuF1CLadOPfZx9OnjSQmFGBVTQiEnPNOpA=
      skip_cleanup: true
      on:
        repo: LuleaUniversityOfTechnology/2018-project-roaster
        branch: master
